### ISSUE TITLE
Fixed model maps path

### ISSUE THREAD

**Issue by H-Sura** [djbozkosz/BlenderMafia4ds#3]
Hello.

In your script mafia_4ds_import.py there is a fixed path to C:/Hry/Mafia/maps/ folder.
Is there a way to change it while the add-on is imported?

Modifying the location does not help. And, when obeying the hardcoded path the below error is shown:

```
Python: Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\mafia_4ds\mafia_4ds_import.py", line 425, in execute
    return exporter.Import(self.filepath)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\mafia_4ds\mafia_4ds_import.py", line 405, in Import
    self.DeserializeFile(reader)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\mafia_4ds\mafia_4ds_import.py", line 394, in DeserializeFile
    result = self.DeserializeMesh(reader, materials, meshes)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\mafia_4ds\mafia_4ds_import.py", line 336, in DeserializeMesh
    meshProps.VisualType   = "0x{:02x}".format(visualType)
TypeError: bpy_struct: item.attr = val: enum "0x03" not found in ('0x00')

location: <unknown location>:-1
```

Thank you.

H

**Comment by H-Sura** [comment]
I see you already have a commit resolving this.

Closing
