### ISSUE TITLE
Unknown location while importing 4ds model

### ISSUE THREAD

**Issue by H-Sura** [djbozkosz/BlenderMafia4ds#4]
Hello.

While trying to import any model of character:

Traceback (most recent call last):
  File "C:\Users\hynek\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\mafia_4ds\mafia_4ds_import.py", line 427, in execute
    return exporter.Import(self.filepath)
  File "C:\Users\hynek\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\mafia_4ds\mafia_4ds_import.py", line 407, in Import
    self.DeserializeFile(reader)
  File "C:\Users\hynek\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\mafia_4ds\mafia_4ds_import.py", line 396, in DeserializeFile
    result = self.DeserializeMesh(reader, materials, meshes)
  File "C:\Users\hynek\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\mafia_4ds\mafia_4ds_import.py", line 338, in DeserializeMesh
    meshProps.VisualType   = "0x{:02x}".format(visualType)
TypeError: bpy_struct: item.attr = val: enum "0x02" not found in ('0x00')

location: <unknown location>:-1

Other models, like houses and so on work fine.

Any idea why?

Thank you

**Comment by ProfanePagane** [comment]
Hi! I had the same problem. The path needs to be defined. Open mafia_4ds_import.py and in it, find the line
file        = bpy.data.images.load(filepath = "C:/Hry/Mafia/maps/{}".format(diffuse), check_existing = True)
And change the path "C:/Hry/Mafia/maps/" to the one where your maps folder is located.

**Comment by djbozkosz** [comment]
Hi,
both errors I have resolved in the latest release [1.0.1](https://github.com/djbozkosz/BlenderMafia4ds/releases):

- added path selector in addon preferences
- fixed error handling for unsupported mesh types (I didn't add support for other mesh types)

Regards,
djbozkosz.
